spring:
#  data:
#    redis:
#      host: 192.168.188.200
#      port: 6379
#      password: 1234
  datasource:
    url: jdbc:mysql://localhost:3306/12306_aggregation?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 1234