
spring:
  cloud:
    gateway:
      routes:
        - id : example
          uri : localhost:${server.port}
          predicates:
            - Path=/exam
          filters:
            - name: TokenValidate
server:
  port: 9090